# path to sample sheet (structured, tab-separated)
samples: reduced_samples_glios.tsv

software:
 Rbin: "R_LIBS=/home/Shared_taupo/Rlib/release-3.9-lib/ /usr/local/R/R-3.6.0/bin/Rscript"


params:
 chromosomes: ['18','19']
 min_coverage: 20
 num_threads: 10

pca:
 labels:
  - id
  - exp
  - sequencing
  - genotype
