---
title: "Feature Differences in different TR settings"
author: "Atreya Choudhury"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    code_folding: hide
    number_sections: no
    fig_crop: yes
---

```{r, setup}
suppressPackageStartupMessages({
  library(ggplot2)
})

source("src/ggtheme.R")

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE, warning = FALSE,
  fig.path = snakemake@params[["plots_dir"]],
  dev = c("png", "svg"),
  dpi = 500
)
```

```{r}
N <- snakemake@params[["N"]]
f <- snakemake@params[["f"]]
data_dir <- dirname(snakemake@input[["det_out"]])
intervals <- read.table(
  paste(data_dir, "/intervals.", N, ".", f, ".tsv", sep = ""),
  col.names = c("chr2", "start2", "end2", "type", "prob.0"),
  header = F
)
sampens <- read.table(
  snakemake@input[["det_out"]],
  header = T
)
jnt <- cbind(sampens, intervals)
output_cols <- grep("^output", colnames(jnt), value = TRUE)
jnt.long <- do.call(rbind, lapply(output_cols, function(col) {
  data.frame(
    start = jnt$start,
    end = jnt$end,
    sample = col,
    sampen = jnt[[col]],
    shannon = jnt$shannon,
    avg_meth = jnt$avg_meth,
    type = jnt$type
  )
}))


meth <- read.table(
  paste(data_dir, "/yamet.", N, ".", f, ".meth.out", sep = ""),
  header = TRUE
)
meth.long <- do.call(rbind, lapply(output_cols, function(col) {
  data.frame(
    meth = meth[[col]]
  )
}))

all.long <- cbind(jnt.long, meth.long)

print(str(all.long))

all.long$type <- factor(all.long$type, levels = c("lmr", "imrCons", "imrRand", "hmr"))


ggplot(all.long, aes(x = meth, y = sampen, color = type)) +
  geom_point(alpha = 0.7) +
  theme_minimal() +
  labs(
    title = "Sample Entropy in different TR settings",
    x = "avg. methylation", y = "sample entropy", color = "TR"
  ) +
  theme_ng() +
  scale_color_viridis_d()

ggplot(jnt, aes(x = avg_meth, y = shannon, color = type)) +
  geom_point(alpha = 0.7) +
  theme_minimal() +
  labs(
    title = "Shannon Entropy in different TR settings (per cell)",
    x = "avg. methylation", y = "Shannon entropy", color = "TR"
  ) +
  theme_ng() +
  scale_color_viridis_d()

ggplot(all.long, aes(x = shannon, y = sampen, color = type)) +
  geom_point(alpha = 0.7) +
  theme_minimal() +
  labs(
    title = "Sample Entropy in different TR settings",
    x = "Shannon entropy", y = "sample entropy", color = "TR"
  ) +
  theme_ng() +
  scale_color_viridis_d()
```
