# path to sample sheet (structured, tab-separated)
samples: samples.tsv

software:
 Rbin: "/usr/local/bin/R"

params:
 chromosomes: ['chr19']
 min_coverage: 20
 num_threads: 4

pca:
 labels:
  - id
  - exp
  - sequencing
  - genotype