# path to sample sheet (structured, tab-separated)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

software:
  Rbin: "/usr/local/bin/R"

params:
  chromosomes: ['chr19']
  mincoverage: 20
  num_threads: 4

pca:
  labels:
    # columns of sample sheet to use for PCA
    - exp
    - sequencing
    - genotype

