---
title: "scMetSimPlots"
author: "Emanuel Sonder"
date: "5/1/2025"
output:
    bookdown::html_document2:
    code_folding: hide
    number_sections: no
    fig_crop: yes
---

```{r, setup}
suppressPackageStartupMessages({
library(data.table)
library(markovchain)
})

source("simPattern.R")

seed <- 43
set.seed(seed)
```

## Load simulation parameters

```{r, load parameters}

```

## Load the real data

```{r, load real data}
metTable <- readRDS("../../sim/met_table_chr5.rds")
cellIds <- setdiff(colnames(metTable), c("chr", "pos"))
cellIds <- cellIds[grepl("E7.5", cellIds)]
cellIds <- sample(cellIds, 100)

metTable <- metTable[,c("chr", "pos", cellIds), with=FALSE]
```

## Param grid

```{r, parameter nb grid for simulations}
nCells <- c(100)
mode <- c("nb", "random")
transMat <- c("est", "hmr", "lmr", "imr_cons", "imr_rand")
covParams <- c("est", "low", "medium", "high")
nCpGs <- c(1e6, 50, 1000, 1e4)
  
paramGridNb <- as.data.table(expand.grid(list("n_cells"=nCells, 
                                              "n_cpgs"=nCpGs, 
                                              "mode"=c("nb"),
                                              "covParams"=covParams,
                                              "transMat"=transMat)))
setorder(paramGridNb, -n_cpgs)
```

```{r, parameter random grid for simulations}
nCells <- c(100)
nCpGs <- c(1e6, 50, 1000, 1e4)
mode <- c("nb", "random")
transMat <- c("est")
transMat <- c("est", "hmr", "lmr", "imr_cons", "imr_rand")
covParams <- c("est", "low", "medium", "high")
  
paramGridRand <- as.data.table(expand.grid(list("n_cells"=nCells, 
                                                "n_cpgs"=nCpGs, 
                                                "mode"=c("random"),
                                                "covParams"=covParams,
                                                "transMat"=transMat)))
```

```{r}
lapply(nCpGs, function(nCpG){
  cpgTable <- write.table(data.table(chr=rep("chrSim", nCpG),
                                   pos=1:nCpG),
                          file=file.path("./sim_data/perCellReports", 
                                         paste0(paste("cpgPositions", nCpG, sep="_"), ".tsv")),
                          sep="\t",
                          row.names=FALSE,
                          quote=FALSE)
})
```

## Simulate

```{r, simulate nb}
for(i in 1:nrow(paramGrid)){
  params <- paramGrid[i, ]
  
  # get the coverage parameters ------------------------------------------------
  
  if(params$covParams=="low"){
    probParams=c(0.03,0.97)
    sizeParams=c(1, 1)
    estimateCovParams=FALSE
  }
  else if(params$covParams=="medium"){
    probParams=c(0.15,0.85)
    sizeParams=c(1.2, 1)
    estimateCovParams=FALSE
  }
  else if(params$covParams=="high"){
    probParams=c(0.5,0.5)
    sizeParams=c(2, 1)
    estimateCovParams=FALSE
  }
  else if(params$covParams=="est"){
    probParams=NULL
    sizeParams=NULL
    estimateCovParams=TRUE
  }
  
  # get the transition probability parameters ----------------------------------
  
  if(params$transMat=="hmr"){
    transMat <- matrix(c(0.2,0.2,0.8,0.8), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="lmr"){
    transMat <- matrix(c(0.8,0.8,0.2,0.2), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="imr_cons"){
    transMat <- matrix(c(0.8,0.2,0.2,0.8), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="imr_rand"){
    transMat <- matrix(c(0.5,0.5,0.5,0.5), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="est"){
    estimateTransMat=TRUE
    transMat <- NULL
  }
  
  if(!is.null(transMat)) colnames(transMat) <- c("0", "1")
  
  
  simTable <- simMetPattern(params$n_cpgs, 
                            params$n_cells,
                            mode=as.character(params$mode),
                            probParams=probParams,
                            sizeParams=sizeParams,
                            states=c('0', '1'),
                            estimateCovParams=estimateCovParams,
                            estimateTransMat=estimateTransMat,
                            transMat=transMat,
                            metTable=metTable,
                            seed=seed)
  params <- lapply(params, as.character)
  saveRDS(simTable, file.path("./sim_data_batch2", 
                    paste0(paste("sim", paste(params, collapse="_"), sep="_"), ".rds")))
  
  cellIds <- setdiff(colnames(simTable), c("pos", "chr"))
  lapply(cellIds, function(cellId){
    
    simCell <- simTable[, c(cellId, "pos", "chr"), with=FALSE]
    simCell <- simCell[complete.cases(simCell),]
    setnames(simCell, cellId, "rate")
    simCell[,met_reads:=fifelse(rate==1,1,0)]
    simCell[,nonmet_reads:=fifelse(rate==0,1,0)]
    simCell <- simCell[,c("chr", "pos", "met_reads", "nonmet_reads", "rate")]
    write.table(simCell, 
              file=file.path("./sim_data_batch2/perCellReports",
                             paste0(paste(cellId, paste(params, collapse="_"), sep="_"), ".tsv")),
              quote=FALSE, sep='\t', row.names=FALSE)
  })
}
```

```{r, simulate random}
paramGrid <- paramGridRand

for(i in 1:nrow(paramGrid)){
  params <- paramGrid[i, ]
  
  # get the coverage parameters ------------------------------------------------

  if(params$covParams=="low"){
    probParams=c(0.03,0.97)
    sizeParams=c(1, 1)
    estimateCovParams=FALSE
  }
  else if(params$covParams=="medium"){
    probParams=c(0.15,0.85)
    sizeParams=c(1.2, 1)
    estimateCovParams=FALSE
  }
  else if(params$covParams=="high"){
    probParams=c(0.5,0.5)
    sizeParams=c(2, 1)
    estimateCovParams=FALSE
  }
  else if(params$covParams=="est"){
    probParams=NULL
    sizeParams=NULL
    estimateCovParams=TRUE
  }
  
  # get the transition probability parameters ----------------------------------
  
  if(params$transMat=="hmr"){
    transMat <- matrix(c(0.2,0.2,0.8,0.8), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="lmr"){
    transMat <- matrix(c(0.8,0.8,0.2,0.2), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="imr_cons"){
    transMat <- matrix(c(0.8,0.2,0.2,0.8), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="imr_rand"){
    transMat <- matrix(c(0.5,0.5,0.5,0.5), nrow=2, ncol=2)
    estimateTransMat=FALSE
  }
  else if(params$transMat=="est"){
    estimateTransMat=TRUE
    transMat <- NULL
  }
  
  if(!is.null(transMat)) colnames(transMat) <- c("0", "1")
  simTable <- simMetPattern(params$n_cpgs, 
                            params$n_cells,
                            mode=as.character(params$mode),
                            probParams=probParams,
                            sizeParams=sizeParams,
                            states=c('0', '1'),
                            estimateCovParams=estimateCovParams,
                            estimateTransMat=estimateTransMat,
                            transMat=transMat,
                            metTable=metTable,
                            seed=seed)
  params <- lapply(params, as.character)
  saveRDS(simTable, file.path("./sim_data_batch2", 
                    paste0(paste("sim", paste(params, collapse="_"), sep="_"), ".rds")))
  
  cellIds <- setdiff(colnames(simTable), c("pos", "chr"))
  lapply(cellIds, function(cellId){
    
    simCell <- simTable[, c(cellId, "pos", "chr"), with=FALSE]
    simCell <- simCell[complete.cases(simCell),]
    setnames(simCell, cellId, "rate")
    simCell[,met_reads:=fifelse(rate==1,1,0)]
    simCell[,nonmet_reads:=fifelse(rate==0,1,0)]
    simCell <- simCell[,c("chr", "pos", "met_reads", "nonmet_reads", "rate")]
    write.table(simCell, 
              file=file.path("./sim_data_batch2/perCellReports",
                             paste0(paste(cellId, paste(params, collapse="_"), sep="_"), ".tsv")),
              quote=FALSE, sep='\t', row.names=FALSE)
  })
}
```