package:
  name: yamet
  version: "0.1.0"

source:
  path: .

requirements:
  build:
    - cmake
    - boost-cpp
  run:
    - boost
    - zlib

about:
  home: https://github.com/imallona/yamet
  summary: "yet another methylation entropy tool"
  license: "GPL"
