import os.path as op
import glob

CHROMS = ['chr' + str(c) for c in range(1, 5)]

SAMPLES = glob.glob(op.join('test_data', '*.bam'))

BAMS = {op.splitext(op.basename(sample))[0] : sample for sample in SAMPLES}
# SORTED = {sample : op.join(sample, 'sorted', sample + '.bam') for sample in BAMS.keys()}
# INDEXED =  {sample : op.join(sample,  sample + '.bam.bai') for sample in BAMS.keys()}
# SPLIT =  expand("{sample}/{sample}_{chrom}.bam",
#             sample =  BAMS.keys(),
#             chrom = CHROMS)
# # SORTED_QN = {sample : op.join(sample, 'split', sample + '_qn_sorted.bam') for sample in BAMS.keys()}

# SORTED_QN =  expand("{sample}/qnsorted_{sample}_{chrom}.bam",
#                     sample =  BAMS.keys(),
#                     chrom = CHROMS)

METHTUPLE = expand("{sample}/qnsorted_{sample}_{chrom}.CG.2.tsv",
                    sample =  BAMS.keys(),
                    chrom = CHROMS)

MINCOVERAGE = 1

AWK = expand("{sample}/qnsorted_{sample}_{chrom}.CG.2_cov_{cov}.tsv",
                    sample =  BAMS.keys(),
                    chrom = CHROMS,
                    cov = MINCOVERAGE)
ENTROPIES = expand("{sample}/qnsorted_{sample}_{chrom}_cov_{cov}_entropy.bed",
                    sample =  BAMS.keys(),
                    chrom = CHROMS,
                    cov = MINCOVERAGE)
METHYLATIONS = expand("{sample}/qnsorted_{sample}_{chrom}_cov_{cov}_methylation.bed",
                    sample =  BAMS.keys(),
                    chrom = CHROMS,
                    cov = MINCOVERAGE)

MERGED_ENTROPY = expand( "{sample}/{sample}_cov_{cov}_entropy.bed.gz",
                           sample = BAMS.keys(),
                           cov = MINCOVERAGE)
MERGED_METHYLATION = expand( "{sample}/{sample}_cov_{cov}_methylation.bed.gz",
                              sample = BAMS.keys(),
                              cov = MINCOVERAGE)

KNITTED_REPORT = expand("{sample}/01_data_visualization_{sample}_cov_{cov}.html",
                        sample = BAMS.keys(),
                        cov = MINCOVERAGE)
                        

print(CHROMS)
print(SAMPLES)
# print(SORTED)
# print(INDEXED)
# print(SPLIT)
# print(SORTED_QN)
# print(AWK)
# print(INDEXED)

rule all:
    input:
        # INDEXED.values(), SPLIT, SORTED_QN, METHTUPLE\
            # METHTUPLE,  AWK, MERGED_ENTROPY, MERGED_METHYLATION
        MERGED_ENTROPY, MERGED_METHYLATION, KNITTED_REPORT
# rule get_entropy:
#        input:
#            output:
#                shell:


rule knit_report:
    input:
        MERGED_ENTROPY, MERGED_METHYLATION
        
    output:
        "{sample}/01_data_visualization_{sample}_cov_{cov}.html"
    script:
        "scripts/01_data_visualization.Rmd"

rule merge_methylations:
    input:
        METHYLATIONS
    output:
        "{sample}/{sample}_cov_{MINCOVERAGE}_methylation.bed.gz"
    shell:
        "cat {input} | bedtools sort | gzip > {output}"
        
rule merge_entropies:
    input:
        ENTROPIES
    output:
        "{sample}/{sample}_cov_{MINCOVERAGE}_entropy.bed.gz"
    shell:
        "cat {input} | bedtools sort | gzip > {output}"
        
rule get_methylation:
    input:
        "{sample}/qnsorted_{sample}_{chrom}.CG.2_cov_{MINCOVERAGE}.tsv"
    output:
        temp("{sample}/qnsorted_{sample}_{chrom}_cov_{MINCOVERAGE}_methylation.bed")
    shell:
        """
        awk '
BEGIN {{OFS=FS="\t"}}
NR == 1 {{next}}
{{
  print $1,$3,$4,"MM"$5";MU"$6";UM"$7";UU"$8,(($5+(0.5*$6)+(0.5*$7))/($5+$6+$7+$8))*1000,$2
}}' {input} > {output}
"""

    
rule get_entropy:
    input:
        "{sample}/qnsorted_{sample}_{chrom}.CG.2_cov_{MINCOVERAGE}.tsv"
    output:
        temp("{sample}/qnsorted_{sample}_{chrom}_cov_{MINCOVERAGE}_entropy.bed")
    shell:
        """
        awk '
BEGIN {{OFS=FS="\t"}}
NR == 1 {{next}}
{{
  H["MM"] = $5
  H["UU"] = $8
  H["UM"] = $7
  H["MU"] = $6
  N  = ($5+$6+$7+$8)
  E = 0
  p = ""
  for (i in H) {{
    if (H[i] != 0) {{
      p = H[i]/N;
      E -=  p * log(p);
    }}
  }}

  print $1,$3,$4,"MM"$5";MU"$6";UM"$7";UU"$8,E,$2

}}' {input} > {output}
"""

rule filter_by_coverage:
       input:
           "{sample}/qnsorted_{sample}_{chrom}.CG.2.tsv"
       output:
           temp("{sample}/qnsorted_{sample}_{chrom}.CG.2_cov_{MINCOVERAGE}.tsv")
       shell:
           """
           awk -v mincov="{MINCOVERAGE}" '
           NR == 1 {{next}}
           {{
            if (($5+$6+$7+$8) >= mincov) print $0
           }}' {input} > {output}
           """
                   
rule run_meththuple:
    input:
        "{sample}/qnsorted_{sample}_{chrom}.bam"
    output:
        temp("{sample}/qnsorted_{sample}_{chrom}.CG.2.tsv")
    shell: """
        set +u;
        source ~/virtenvs/methtuple/bin/activate
        methtuple -m 2 --methylation-type CG {input}    
        deactivate
        set -u;
        """
    
rule sort_by_queryname:
    input:
        "{sample}/{sample}_{chrom}.bam"
    output:
        temp("{sample}/qnsorted_{sample}_{chrom}.bam")
        
    shell:
        """
        samtools sort -n {input} {output}
        mv {output}.bam {output}"""

    
rule split_by_chrom:
    input:
        "{sample}/{sample}.bam"
        # lambda wildcards, attempt: attempt * 100
    output:
        temp("{sample}/{sample}_{chrom}.bam")
    shell:
        "samtools view -b {input} {wildcards.chrom} > {output}"
 
rule samtools_sort:
    input:
        "test_data/{sample}.bam"
    output:
        temp("{sample}/{sample}.bam")
    shell:
        """
        samtools sort {input} {output}
        mv {output}.bam {output}
        samtools index {output}
        """


