# path to sample sheet (structured, tab-separated)
samples: reduced_samples_glios.tsv

software:
 Rbin: "/usr/local/bin/R"

params:
 chromosomes: ['18','19']
 min_coverage: 20
 num_threads: 10

pca:
 labels:
  - id
  - exp
  - sequencing
  - genotype
