name: cppcheck-annotations

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: cppcheck-annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run cppcheck-annotation-action
        uses: Konstantin343/cppcheck-annotation-action@v1.1
        with:
          std: 'c++14'
          platform: 'unix64'
          log-level: 'verbose'

      - name: Annotate lines with errors
        uses: yuzutech/annotations-action@v0.5.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'Results of CppCheck'
          input: 'annotations.json'
