name: cppcheck-annotations

on:
  push:

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          skip_preprocessor: disable
          enable: all #performance,portability,warning
          exclude_check: ./__tests__/exclude/
          inconclusive: disable
          inline_suppression: disable
          force_language: c++
          force: enable
          max_ctu_depth: 12
          platform: disable
          output_file: cppcheck_report.txt
          other_options: --bug-hunting --verbose

      - name: show cppcheck report
        run: |
          cat cppcheck_report.txt
