name: check_unsupported_g++

on:
  workflow_dispatch:
  pull_request:

jobs:
  unsupported_gpp_should_fail:
    runs-on: self-hosted
    strategy:       
        matrix:
            compiler: [ {cpp: g++-12, c: gcc-12} ]
        fail-fast: false
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Build and test_0
        env:
          CC:   ${{ matrix.compiler.c }}
          CXX:  ${{ matrix.compiler.cpp }}
        run: |
          cd method
          bash build.sh

          cd ../test
          ~/.local/bin/yamet \
              --tsv      test_0/in/cell1.bed.gz \
              --ref      test_0/in/ref.bed.gz \
              --bed      test_0/in/regions.bed \
              --det-out  current_test_0.out

          echo 'Diff expected vs produced'

          diff test_0/out/detailed.out \
               current_test_0.out || test $? -eq 0 || echo 'Failed as expected'

  supported_gpp_should_work:
    runs-on: self-hosted
    strategy:       
        matrix:
            compiler: [ {cpp: g++-13, c: gcc-13} ]
        fail-fast: false
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Build and test_0
        env:
          CC:   ${{ matrix.compiler.c }}
          CXX:  ${{ matrix.compiler.cpp }}
        run: |
          cd method
          bash build.sh

          cd ../test
          ~/.local/bin/yamet \
              --tsv      test_0/in/cell1.bed.gz \
              --ref      test_0/in/ref.bed.gz \
              --bed      test_0/in/regions.bed \
              --det-out  current_test_0.out

          echo 'Diff expected vs produced'

          diff test_0/out/detailed.out \
               current_test_0.out
