name: check_unsupported_g++

on:
  workflow_dispatch:
  pull_request:

jobs:
  unsupported_gpp_should_fail:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [{ cpp: g++-12, c: gcc-12 }]
      fail-fast: false
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Installs
        run: |
          sudo apt update && sudo apt install -y libboost-program-options-dev zlib1g-dev

      - name: Build and test_0
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cpp }}
        run: |
          cd method
          bash build.sh

          cd ../test
          ../method/build/yamet \
              test_0/in/cell1.bed.gz \
              -r test_0/in/ref.bed.gz \
              -i test_0/in/regions.bed \
              --det-out  current_test_0.out

          echo 'Diff expected vs produced'

          diff test_0/out/detailed.out \
              current_test_0.out || test $? -eq 0 || echo 'Failed as expected'

  supported_gpp_should_work:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [{ cpp: g++-13, c: gcc-13 }]
      fail-fast: false
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Installs
        run: |
          sudo apt update && sudo apt install -y libboost-program-options-dev zlib1g-dev

      - name: Build and test_0
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cpp }}
        run: |
          cd method
          bash build.sh

          cd ../test
          ../method/build/yamet \
              test_0/in/cell1.bed.gz \
              -r test_0/in/ref.bed.gz \
              -i test_0/in/regions.bed \
              --det-out  current_test_0.out

          echo 'Diff expected vs produced'

          diff test_0/out/detailed.out \
              current_test_0.out
