on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd method
          export PREFIX="."
          bash build.sh

      - name: Memory leak test
        uses: LazyPanda07/check-memory-leaks@v1.4
        with:
          path: bin
          name: yamet
          max-threads: 1
          pre-execute: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)
          args: "--tsv" "tests/test_0/in/cell1.bed.gz" "--ref" "tests/test_0/in/ref.bed.gz" "--bed" "tests/test_0/in/regions.bed" "--det-out" "current_test_0.out"
