name: memleaks

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "method/src/**.cpp"
      - "method/CMakeLists.txt"
      - ".github/workflows/memleaks.yml"

env:
  PREFIX: $HOME/build/

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: workflow/envs/yamet.yml
          activate-environment: yamet
          conda-config: channel_priority=strict

      - name: Install valgrind
        run: sudo apt update && sudo apt install -y valgrind

      - name: Build and valgrind
        run: |
          mkdir -p $PREFIX
          cd method
          ## export PREFIX=$PREFIX # ???
          bash build.sh
          ## ls -lR $PREFIX

          ## echo 'Permissions'
          ## cd $PREFIX/bin
          ## chmod +x yamet

          echo 'Pre valgrind call'

          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)
          export PATH=$(pwd):$PREFIX/bin:$PATH

          echo 'Valgrind call'
          valgrind --leak-check=full \
            --show-leak-kinds=all \
            --track-origins=yes \
            --verbose \
            ./build/yamet \
              -c $GITHUB_WORKSPACE/test/test_0/in/cell1.bed.gz \
              -r $GITHUB_WORKSPACE/test/test_0/in/ref.bed.gz \
              -i $GITHUB_WORKSPACE/test/test_0/in/regions.bed \
              --det-out valgrind_test_0.out
