name: Cross-Platform Build

on:
  workflow_dispatch: null
  push:
    tags:
      - "v*"
  pull_request:
    paths:
      - "method/**"
      - ".github/workflows/tar.yml"

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew update && brew install boost && brew install cli11

      - name: Build
        run: |
          cd method
          cmake -S. \
            -Bbuild \
            -DVERSION=${{ github.ref_name }} \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCPACK_GENERATOR=TGZ \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/ \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake --verbose

      - name: Create GitHub Release and upload tarball
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          files: method/yamet-*.tar.gz

  build-linux:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: workflow/envs/yamet.yml
          activate-environment: yamet
          conda-config: channel_priority=strict

      - name: Build
        run: |
          cd method
          cmake -S. \
            -Bbuild \
            -DVERSION=${{ github.ref_name }} \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCPACK_GENERATOR=DEB \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake --verbose

      - name: Create GitHub Release and upload tarball
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          files: method/yamet-*.deb
