name: Cross-Platform Build

on:
  workflow_dispatch: null
  push:
    tags:
      - "v*"
  pull_request:
    paths:
      - "method/**"
      - ".github/workflows/tar.yml"

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew update && brew install boost && brew install cli11

      - name: Build
        run: |
          cd method
          cmake -S. \
            -Bbuild \
            -DVERSION=${{ github.ref_name }} \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCPACK_GENERATOR=TGZ \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/ \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake --verbose

      - name: Create GitHub Release and upload tarball
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          files: method/yamet-*.tar.gz

  build-linux:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y libboost-iostreams-dev
          wget -q https://github.com/CLIUtils/CLI11/archive/refs/tags/v2.4.2.tar.gz -O /tmp/cli11.tar.gz
          tar -xzf /tmp/cli11.tar.gz -C /tmp
          cmake -S /tmp/CLI11-2.4.2 -B /tmp/cli11-build -DCLI11_TESTING=OFF -DCLI11_EXAMPLES=OFF
          sudo cmake --install /tmp/cli11-build

      - name: Build
        run: |
          cd method
          cmake -S. \
            -Bbuild \
            -DVERSION=${{ github.ref_name }} \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCPACK_GENERATOR=DEB \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake --verbose

      - name: Create GitHub Release and upload tarball
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          files: method/yamet-*.deb
