name: Cross-Platform Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew update && brew install boost

      - name: Build
        run: |
          cd method
          cmake -S. \
            -Bbuild \
            -DZLIB_ROOT="/opt/homebrew/opt/zlib" \
            -DVERSION=${{ github.ref_name }} \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCPACK_GENERATOR=TGZ \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/ \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake --verbose

      - name: Create GitHub Release and upload tarball
        uses: softprops/action-gh-release@v2
        with:
          files: method/yamet-*.tar.gz

  build-linux:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libboost-program-options-dev zlib1g-dev

      - name: Build
        run: |
          cd method
          cmake -S. \
            -Bbuild \
            -DZLIB_ROOT="/usr/include" \
            -DVERSION=${{ github.ref_name }} \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCPACK_GENERATOR=DEB \
            -DCPACK_PACKAGING_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cpack --config build/CPackConfig.cmake --verbose

      - name: Create GitHub Release and upload tarball
        uses: softprops/action-gh-release@v2
        with:
          files: method/yamet-*.deb
