name: build_and_test

on:
  workflow_dispatch: 
  pull_request:
    # types: [assigned, opened, synchronize, reopened]
    # paths: ['.github/workflows/test.yml', '**/Makefile', '**/*.h', '**/*.hpp', '**/*.c', '**/*.cpp']

# env:
#   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_ubuntu_latest_cuda:
    runs-on: self-hosted
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          cd method
          make
       
      - name: Test_0
        run: |
          cd test
          ../method/yamet \
              --tsv      test_0/in/cell1.bed.gz \
              --ref      test_0/in/ref.bed.gz \
              --bed      test_0/in/regions.bed \
              --det-out  current_test_0.out

          echo 'Diff expected vs produced'
          
          diff test_0/out/detailed.out \
               current_test_0.out
          
      - name: Test_1
        run: |
          cd test
          ../method/yamet \
              --tsv      test_1/in/simulations.tsv \
              --ref      test_1/in/reference.tsv \
              --bed      test_1/in/regions.bed \
              --det-out  current_test_1.out &> current_test_1.stdout
          
          echo 'Diff expected vs produced detailed output'

          diff test_1/out/detailed.out \
               current_test_1.out

          echo 'Diff expected vs produced stdout'

          diff test_1/out/stdout \
               current_test_1.stdout