name: build_and_test
on:
  workflow_dispatch: null
  pull_request:

jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
      - name: Installs
        run: |
          sudo apt update && sudo apt install -y libboost-program-options-dev libboost-iostreams-dev
      - name: Build
        run: |
          cd method
          bash build.sh
      - name: Test Ref Parsing
        run: |
          cd test
          ../method/build/yamet \
              test_parse/in/simulations.tsv \
              -r test_parse/in/reference.tsv \
              -i test_parse/in/regions.bed \
              --print-reference \
              --print-sampens F &> current_test_parse.stdout

          echo 'Diff expected vs produced stdout'

          diff test_parse/out/stdout \
              current_test_parse.stdout
      - name: Test Avg Meth singlecore
        if: always()
        run: |
          cd test
          ../method/build/yamet \
              test_avg/in/simulations.*.tsv \
              -r test_avg/in/reference.tsv \
              -i test_avg/in/regions.bed \
              --meth-out current_test_avg.out \
              --cores 1 &> current_test_avg.stdout

          echo 'Diff expected vs produced avg meth output'

          diff test_avg/out/meth.out \
              current_test_avg.out

          echo 'Diff expected vs produced stdout'

          diff test_avg/out/stdout \
              current_test_avg.stdout

      - name: Test Avg Meth multiple reports default
        if: always()
        run: |
          cd test
          ../method/build/yamet \
              test_avg/in/simulations.*.tsv \
              -r test_avg/in/reference.tsv \
              -i test_avg/in/regions.bed \
              --meth-out current_test_avg.out &> current_test_avg.stdout

          echo 'Diff expected vs produced avg meth output'

          diff test_avg/out/meth.out \
              current_test_avg.out

          echo 'Diff expected vs produced stdout'

          diff test_avg/out/stdout \
              current_test_avg.stdout
      - name: Test_0 one report
        if: always()
        run: |
          cd test
          ../method/build/yamet \
              test_0/in/cell1.bed.gz \
              -r test_0/in/ref.bed.gz \
              -i test_0/in/regions.bed \
              --print-sampens F \
              --det-out current_test_0.out

          echo 'Diff expected vs produced'

          diff test_0/out/detailed.out \
              current_test_0.out
      - name: Test_0 two reports
        if: always()
        run: |
          cd test
          ../method/build/yamet \
              test_0/in/cell1.bed.gz test_0/in/cell1.bed.gz \
              -r test_0/in/ref.bed.gz \
              -i test_0/in/regions.bed \
              --print-sampens F \
              --det-out current_test_0.out
           ## no diff because we don't have the true outputs stored;
           ##  exit code is enough
      - name: Test_1
        if: always()
        run: |
          cd test
          ../method/build/yamet \
              test_1/in/simulations.tsv \
              -r test_1/in/reference.tsv \
              -i test_1/in/regions.bed \
              --det-out current_test_1.out &> current_test_1.stdout

          echo 'Diff expected vs produced detailed output'

          diff test_1/out/detailed.out \
              current_test_1.out

          echo 'Diff expected vs produced stdout'

          diff test_1/out/stdout \
              current_test_1.stdout
