---
name: build_and_test
on:
  workflow_dispatch: null
  pull_request: null
jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
      - name: Installs
        run: |
          sudo apt-get install zlib1g-dev build-essential libboost-program-options-dev libboost-test-dev
      - name: Build
        run: |
          cd method
          bash build.sh
      - name: Test Ref Parsing
        run: |
          cd test
          ../method/build/yamet \
              --tsv      test_parse/in/simulations.tsv \
              --ref      test_parse/in/reference.tsv \
              --bed      test_parse/in/regions.bed \
              --print-ref --print-sampens F &> current_test_parse.stdout

          echo 'Diff expected vs produced stdout'

          diff test_parse/out/stdout \
               current_test_parse.stdout
      - name: Test_0
        run: |
          cd test
          ../method/build/yamet \
              --tsv      test_0/in/cell1.bed.gz \
              --ref      test_0/in/ref.bed.gz \
              --bed      test_0/in/regions.bed \
              --det-out  current_test_0.out
              --print-sampens F

          echo 'Diff expected vs produced'

          diff test_0/out/detailed.out \
               current_test_0.out
      - name: Test_1
        run: |
          cd test
          ../method/build/yamet \
              --tsv      test_1/in/simulations.tsv \
              --ref      test_1/in/reference.tsv \
              --bed      test_1/in/regions.bed \
              --det-out  current_test_1.out &> current_test_1.stdout

          echo 'Diff expected vs produced detailed output'

          diff test_1/out/detailed.out \
               current_test_1.out

          echo 'Diff expected vs produced stdout'

          diff test_1/out/stdout \
               current_test_1.stdout
