---
title: "CRC Stats"
author: "Atreya Choudhury"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    code_folding: hide
    theme: flatly
    number_sections: no
    fig_crop: yes
---

```{r, setup}
suppressPackageStartupMessages({
  library(readr)
  library(ggplot2)
  library(ComplexHeatmap)
  library(BiocParallel)
  library(limma)
})
```

```{r}
filepaths <- list.files(
  snakemake@params[["yamet"]],
  pattern = "bookended\\.custom\\..*\\.det\\.out\\.gz$", full.names = T
)

process_reports <- function(filepath) {
  out_path <- gsub("\\.det", "", filepath)
  m_out_path <- gsub("\\.det\\.", ".meth.", filepath)

  out <- read_tsv(out_path, show_col_types = FALSE, na = "-1")
  se <- read_tsv(filepath, show_col_types = FALSE, na = "-1")
  ms <- read_tsv(m_out_path, show_col_types = FALSE, na = "-1")

  rwnms <- paste0(se$chr, ":", se$start, "-", se$end)

  shannon <- se[, c("shannon", "avg_meth")]

  se <- as.matrix(se[, grep("singleC", colnames(se))])
  ms <- as.matrix(ms[, grep("singleC", colnames(ms))])

  rownames(se) <- rwnms
  rownames(ms) <- rwnms

  return(
    list(
      shannon = shannon,
      sampen = se, meth = ms, cell_meth = out$avg_meth
    )
  )
}

param <- MulticoreParam(workers = snakemake@threads)
all_data <- bplapply(filepaths, process_reports, BPPARAM = param)
sampens <- do.call(cbind, lapply(all_data, \(x) x$sampen))
meths <- do.call(cbind, lapply(all_data, \(x) x$meth))

annot <- read_tsv(snakemake@input[["annotation"]], show_col_types = FALSE)
rownames(annot) <- rownames(sampens)
get_row_annotations <- function(regions) {
  rowAnnotation(tile_annotation = as.matrix(data.frame(
    pmd = annot[regions, "pmds_pmd"],
    hmd = annot[regions, "hmds_pmd"],
    H3K27me3 = annot[regions, "H3K27me3_chip"],
    H3K9me3 = annot[regions, "H3K9me3_chip"],
    H3K4me3 = annot[regions, "H3K4me3_chip"],
    laminb1 = annot[regions, "laminb1_lad"],
    X8_Quiescent = annot[regions, "8_Quiescent_hmm"]
  )))
}

meta <- data.frame(
  colname = colnames(sampens),
  patient = sapply(strsplit(colnames(sampens), "_"), \(x) x[3]),
  subloc = sapply(strsplit(colnames(sampens), "_"), \(x) x[4]),
  cell_meth = unlist(lapply(all_data, \(x) x$cell_meth), recursive = FALSE)
)
meta$loc <- substr(meta$subloc, 1, 2)
meta$loc <- relevel(factor(meta$loc), ref = "NC")
meta <- meta[order(as.integer(meta$loc), meta$subloc, meta$patient), ]
sampens <- sampens[, meta$colname]
meths <- meths[, meta$colname]

groups <- unique(meta[c("subloc", "patient")])
groups <- groups[
  order(substr(groups$subloc, 1, 2), groups$subloc, groups$patient),
]
sub_sampens <- do.call(cbind, lapply(seq_len(nrow(groups)), \(i) {
  cols <- meta$colname[
    meta$patient == groups$patient[i] & meta$subloc == groups$subloc[i]
  ]
  rowMeans(sampens[, cols, drop = FALSE], na.rm = TRUE)
}))
colnames(sub_sampens) <- paste(groups$subloc, groups$patient, sep = "_")

sub_meths <- do.call(cbind, lapply(seq_len(nrow(groups)), \(i) {
  cols <- meta$colname[
    meta$patient == groups$patient[i] & meta$subloc == groups$subloc[i]
  ]
  rowMeans(meths[, cols, drop = FALSE], na.rm = TRUE)
}))
colnames(sub_meths) <- paste(groups$subloc, groups$patient, sep = "_")
```

```{r}
row_na_frac <- \(x) mean(is.na(x)) >= 0.5
rows_too_sparse <- apply(sub_sampens, 1, row_na_frac) |
  apply(sub_meths, 1, row_na_frac)

dim(sub_sampens)
dim(sub_meths)

sub_sampens <- sub_sampens[!rows_too_sparse, , drop = FALSE]
sub_meths <- sub_meths[!rows_too_sparse, , drop = FALSE]

dim(sub_sampens)
dim(sub_meths)

colnames(sub_meths)
```

```{r}
c02_nc <- data.frame(y = sub_sampens[, "NC_CRC02"], x = sub_meths[, "NC_CRC02"])
c02_nc <- na.omit(c02_nc)
sampled_data <- c02_nc[sample(nrow(c02_nc), 5000), ]

ggplot(sampled_data, aes(x = x, y = y)) +
  geom_point(alpha = 0.6, size = 0.6) +
  labs(
    title = "Normal Cells in CRC02",
    x = "Average Methylation",
    y = "Sample Entropy"
  ) +
  theme_minimal()
```

```{r}
crc02_pt_cols <- grep("^PT[0-9]+_CRC02$", colnames(sub_sampens), value = TRUE)
y_vals <- rowMeans(sub_sampens[, crc02_pt_cols, drop = FALSE], na.rm = TRUE)
x_vals <- rowMeans(sub_meths[, crc02_pt_cols, drop = FALSE], na.rm = TRUE)
c02_pt <- data.frame(y = y_vals, x = x_vals)
c02_pt <- na.omit(c02_pt)
sampled_data <- c02_pt[sample(nrow(c02_pt), 5000), ]

ggplot(sampled_data, aes(x = x, y = y)) +
  geom_point(alpha = 0.6, size = 0.6) +
  labs(
    title = "Primary Tumour Cells in CRC02",
    x = "Average Methylation",
    y = "Sample Entropy"
  ) +
  theme_minimal()
```

```{r}
c04_nc <- data.frame(y = sub_sampens[, "NC_CRC04"], x = sub_meths[, "NC_CRC04"])
c04_nc <- na.omit(c04_nc)
sampled_data <- c04_nc[sample(nrow(c04_nc), 5000), ]

ggplot(sampled_data, aes(x = x, y = y)) +
  geom_point(alpha = 0.6, size = 0.6) +
  labs(
    title = "Normal Cells in CRC04",
    x = "Average Methylation",
    y = "Sample Entropy"
  ) +
  theme_minimal()
```

```{r}
crc04_pt_cols <- grep("^PT[0-9]+_CRC04$", colnames(sub_sampens), value = TRUE)
y_vals <- rowMeans(sub_sampens[, crc04_pt_cols, drop = FALSE], na.rm = TRUE)
x_vals <- rowMeans(sub_meths[, crc04_pt_cols, drop = FALSE], na.rm = TRUE)
c04_pt <- data.frame(y = y_vals, x = x_vals)
c04_pt <- na.omit(c04_pt)
sampled_data <- c04_pt[sample(nrow(c04_pt), 5000), ]

ggplot(sampled_data, aes(x = x, y = y)) +
  geom_point(alpha = 0.6, size = 0.6) +
  labs(
    title = "Primary Tumour Cells in CRC04",
    x = "Average Methylation",
    y = "Sample Entropy"
  ) +
  theme_minimal()
```

```{r}
c10_nc <- data.frame(y = sub_sampens[, "NC_CRC10"], x = sub_meths[, "NC_CRC10"])
c10_nc <- na.omit(c10_nc)
sampled_data <- c10_nc[sample(nrow(c10_nc), 5000), ]

ggplot(sampled_data, aes(x = x, y = y)) +
  geom_point(alpha = 0.6, size = 0.6) +
  labs(
    title = "Normal Cells in CRC10",
    x = "Average Methylation",
    y = "Sample Entropy"
  ) +
  theme_minimal()
```

```{r}
crc10_pt_cols <- grep("^PT[0-9]+_CRC10$", colnames(sub_sampens), value = TRUE)
y_vals <- rowMeans(sub_sampens[, crc10_pt_cols, drop = FALSE], na.rm = TRUE)
x_vals <- rowMeans(sub_meths[, crc10_pt_cols, drop = FALSE], na.rm = TRUE)
c10_pt <- data.frame(y = y_vals, x = x_vals)
c10_pt <- na.omit(c10_pt)
sampled_data <- c10_pt[sample(nrow(c10_pt), 5000), ]

ggplot(sampled_data, aes(x = x, y = y)) +
  geom_point(alpha = 0.6, size = 0.6) +
  labs(
    title = "Primary Tumour Cells in CRC10",
    x = "Average Methylation",
    y = "Sample Entropy"
  ) +
  theme_minimal()
```

```{r}
rowwise_lm <- function(i) {
  df <- data.frame(
    sampen = sub_sampens[i, ],
    meth = sub_meths[i, ],
    loc = factor(substr(groups$subloc, 1, 2)),
    patient = groups$patient
  )
  df$loc <- relevel(df$loc, ref = "NC")

  fit <- try(lm(sampen ~ meth + I(meth^2) + loc + patient, data = df), silent = T)
  s <- summary(fit)$coefficients

  if (!("locPT" %in% rownames(s))) {
    return(rep(NA, 5))
  }

  c(
    estimate  = s["locPT", "Estimate"],
    std_error = s["locPT", "Std. Error"],
    t_value   = s["locPT", "t value"],
    p_value   = s["locPT", "Pr(>|t|)"],
    df        = df.residual(fit)
  )
}

coefs_list <- bplapply(seq_len(nrow(sub_sampens)), rowwise_lm, BPPARAM = param)
head(coefs_list)

coefs_df <- do.call(rbind, coefs_list)
colnames(coefs_df) <- c("estimate", "std_error", "t_value", "p_value", "df")
coefs_df <- as.data.frame(coefs_df)

dim(coefs_df)

coefs_df[] <- lapply(coefs_df, as.numeric)

valid <- complete.cases(coefs_df)
coefs_valid <- coefs_df[valid, ]

dim(coefs_valid)

s2 <- coefs_valid$std_error^2
df_resid <- coefs_valid$df
squeezed <- squeezeVar(var = s2, df = df_resid)

moderated_t <- coefs_valid$estimate / sqrt(squeezed$var.post)
moderated_p <- 2 * pt(-abs(moderated_t), df = squeezed$df.prior + df_resid)
adj_p <- p.adjust(moderated_p, method = "BH")

coefs_valid$moderated_t <- moderated_t
coefs_valid$moderated_p <- moderated_p
coefs_valid$adj_p <- adj_p

coefs_df$moderated_t <- NA
coefs_df$moderated_p <- NA
coefs_df$adj_p <- NA
coefs_df[valid, c("moderated_t", "moderated_p", "adj_p")] <- coefs_valid[, c("moderated_t", "moderated_p", "adj_p")]

dim(coefs_df)
head(coefs_df)

sorted_idx <- order(coefs_df$adj_p, na.last = NA)

top_2k_idx <- sorted_idx[1:2000]

top_entropy <- sub_sampens[top_2k_idx, ]
top_meth <- sub_meths[top_2k_idx, ]
head(top_meth)
```

```{r}
row_ha <- get_row_annotations(rownames(top_meth))

ht <- Heatmap(
  top_entropy,
  name = "sampens",
  cluster_columns = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE
)
ht_drawn <- draw(ht)
row_ordered <- row_order(ht_drawn)

column_ha <- HeatmapAnnotation(
  loc = substr(groups$subloc, 1, 2),
  subloc = groups$subloc,
  patient = groups$patient
)

Heatmap(top_entropy[row_ordered, ],
  name = "sampens",
  top_annotation = column_ha,
  right_annotation = row_ha,
  show_row_names = FALSE,
  show_column_names = FALSE,
  cluster_columns = FALSE,
  cluster_rows = FALSE
) +
  Heatmap(top_meth[row_ordered, ],
    name = "meths",
    show_row_names = FALSE,
    show_column_names = FALSE,
    cluster_columns = FALSE,
    cluster_rows = FALSE
  )
```