---
title: "CRC Deletions"
author: "Atreya Choudhury"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    code_folding: hide
    theme: flatly
    number_sections: no
    fig_crop: yes
---

```{r, setup}
suppressPackageStartupMessages({
  library(readr)
  library(ggplot2)
  library(ComplexHeatmap)
  library(BiocParallel)
  library(limma)
})
```

```{r logging, include = FALSE}
log <- file(snakemake@log$log, open = "wt")
sink(log)
sink(log, type = "message")
```

```{r}
filepaths <- list.files(
  snakemake@params[["output_path"]],
  pattern = paste0(
    snakemake@wildcards[["win_size"]], "_(.*)\\.det\\.out\\.gz$"
  ), full.names = TRUE
)

process_reports <- function(filepath) {
  out_path <- gsub("\\.det", "", filepath)
  m_out_path <- gsub("\\.det\\.", ".meth.", filepath)

  out <- read_tsv(out_path, show_col_types = FALSE, na = "-1")
  se <- read_tsv(filepath, show_col_types = FALSE, na = "-1")
  ms <- read_tsv(m_out_path, show_col_types = FALSE, na = "-1")

  rwnms <- paste0(se$chr, ":", se$start, "-", se$end)

  shannon <- se[, c("shannon", "avg_meth")]

  se <- as.matrix(se[, grep("singleC", colnames(se))])
  ms <- as.matrix(ms[, grep("singleC", colnames(ms))])

  rownames(se) <- rwnms
  rownames(ms) <- rwnms

  return(
    list(
      shannon = shannon,
      sampen = se, meth = ms, cell_meth = out$avg_meth
    )
  )
}

param <- MulticoreParam(workers = snakemake@threads)
all_data <- bplapply(filepaths, process_reports, BPPARAM = param)
sampens <- do.call(cbind, lapply(all_data, \(x) x$sampen))
meths <- do.call(cbind, lapply(all_data, \(x) x$meth))

meta <- data.frame(
  colname = colnames(sampens),
  patient = sapply(strsplit(colnames(sampens), "_"), \(x) x[3]),
  subloc = sapply(strsplit(colnames(sampens), "_"), \(x) x[4]),
  cell_meth = unlist(lapply(all_data, \(x) x$cell_meth), recursive = FALSE)
)
meta$loc <- substr(meta$subloc, 1, 2)
meta$loc <- relevel(factor(meta$loc), ref = "NC")
meta <- meta[order(as.integer(meta$loc), meta$subloc, meta$patient), ]

sampens <- sampens[, meta$colname]
meths <- meths[, meta$colname]

groups <- unique(meta[c("subloc", "patient")])
groups <- groups[
  order(substr(groups$subloc, 1, 2), groups$subloc, groups$patient),
]
sub_sampens <- do.call(cbind, lapply(seq_len(nrow(groups)), \(i) {
  cols <- meta$colname[
    meta$patient == groups$patient[i] & meta$subloc == groups$subloc[i]
  ]
  rowMeans(sampens[, cols, drop = FALSE], na.rm = TRUE)
}))
colnames(sub_sampens) <- paste(groups$subloc, groups$patient, sep = "_")

sub_meths <- do.call(cbind, lapply(seq_len(nrow(groups)), \(i) {
  cols <- meta$colname[
    meta$patient == groups$patient[i] & meta$subloc == groups$subloc[i]
  ]
  rowMeans(meths[, cols, drop = FALSE], na.rm = TRUE)
}))
colnames(sub_meths) <- paste(groups$subloc, groups$patient, sep = "_")
colnames(sub_meths)

dim(sub_sampens)
```

```{r, fig.asp=1.6}
chrs <- sapply(
  strsplit(rownames(sub_sampens), ":"), function(x) gsub("chr", "", x[1])
)
row_ha <- rowAnnotation(
  chr = chrs,
  col = list(chr = setNames(
    rep(c("black", "white"), length.out = length(unique(chrs))),
    unique(chrs)
  )),
  border = T,
  show_legend = FALSE,
  show_annotation_name = TRUE
)

column_ha <- HeatmapAnnotation(
  loc = substr(groups$subloc, 1, 2),
  subloc = groups$subloc,
  patient = groups$patient
)

Heatmap(sub_sampens,
  name = "sampens",
  top_annotation = column_ha,
  left_annotation = row_ha,
  cluster_columns = FALSE,
  cluster_rows = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE
)
```